services:
  stremio:
    build:
      context: .
      dockerfile: StremioAddon/Dockerfile
    env_file:
        - .env
    volumes:
      - "./stremioData:${STREMIO_DATA}"
    ports:
      - "420:8080"
  
  worker:
    build:
      context: .
      dockerfile: ResourceFetcher/Dockerfile
    env_file: 
      - .env
    volumes:
      - "./stremioData:${RESOURCE_FETCHER_OUTPUT_PATH}"